language: php 

compiler:
  - g++
  - clang++

os:
  - linux
#  - osx

php:
  # - 7.0
  - 7.1
  - 7.2

notifications:
  email: team@swoole.com

before_script:
    - pecl channel-update pecl.php.net && yes no | pecl install swoole
    - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - cmake . && make

script:
    - ./build.sh
    - ./bin/phpx --version
    - exit 0


